# Sends a Repository Dispatch Event to the api-specs repo to close an existing PR
name: Close API Specs PR

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  send_dispatch:
    name: Close API Specs PR
    runs-on: ubuntu-latest
    steps:
      - name: Send Closed Repository Dispatch Event
        if: ${{ github.event.pull_request.merged == false }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.NUMBERS_DEVOPS_GITHUB_TOKEN }}
          repository: Bandwidth/api-specs
          event-type: github.event.pull_request.merged == true && 'Numbers-Merge' || 'Numbers-Close'
          client-payload: '{"branchName": "${{ github.head_ref }}", "prNumber":"${{ github.event.number }}", "originRepo": "${{ github.repository }}"}'
