name: Open/Update Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'

jobs:

  generate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - uses: Bandwidth/github-actions/openapi-preprocessor@BWDB-14042-oas-preprocessor
#        with:
#          input_file: 'spec/numbers.json'
#          output_file: 'numbers_all.json'
#
#      - uses: ./spec-splitter

      # to be replaced with using the spec splitter
      - run: cp spec/numbers.yaml spec/numbers_external.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: specs
          path: spec/numbers_external.yaml

#      - uses: actions/upload-artifact@v3
#        with:
#          name: specs
#          path: numbers_internal.json

      - name: Send Repository Dispatch Event
        uses: Bandwidth/repository-dispatch-action@v2.0.0
        with:
          token: ${{ secrets.NUMBERS_DEVOPS_GITHUB_TOKEN }}
          repository: api-specs
          event-type: ${{ github.event.action == 'synchronize' && 'Numbers-Update' || 'Numbers-Open' }}
          client-payload: '{"branchName": "${{ github.head_ref }}", "prNumber":"${{ github.event.number }}", "originRepo": "numbers-us-api-spec", "author": "${{ github.event.sender.login }}", "draftPr": ${{ github.event.pull_request.draft }}, "runId": "${{ github.run_id }}"}'
