name: Open/Update Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'

jobs:

  generate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: mrmeyers99/openapi-preprocessor@main
        with:
          input_file: 'spec/numbers.yml'
          output_file: 'numbers_all.yml'

#      - uses: ./spec-splitter

      # to be replaced with using the spec splitter
      - run: cp spec/numbers_all.yml spec/numbers_external.yml

      - name: Validate spec
        run: yamllint -d relaxed spec/numbers_external.yml

      - uses: actions/upload-artifact@v3
        with:
          name: specs
          path: spec/numbers_external.yml

#      - uses: actions/upload-artifact@v3
#        with:
#          name: specs
#          path: numbers_internal.json

  open-update-pr:
    needs: generate-specs
    runs-on: ubuntu-latest
    steps:

      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.NUMBERS_DEVOPS_GITHUB_TOKEN }}
          repository: Bandwidth/api-specs
          event-type: ${{ github.event.action == 'synchronize' && 'Numbers-Update' || 'Numbers-Open' }}
          client-payload: '{"branchName": "${{ github.head_ref }}", "prNumber":"${{ github.event.number }}", "originRepo": "${{ github.repository }}", "author": "${{ github.event.sender.login }}", "draftPr": ${{ github.event.pull_request.draft }}, "runId": "${{ github.run_id }}"}'
